### ISSUE TITLE
Forwarding a message is broken

### ISSUE THREAD

**Issue by jasonmunro** [jasonmunro/cypht#557]
When trying to forward a message the code is calling attach_file() which is no longer defined. Looks like this bit was missed when we changed how attachments are handled. Easy to trigger, just try forwarding a message.

```[01-Mar-2022 19:22:01 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function attach_file() in /home/jason/cypht/modules/imap/handler_modules.php:58
Stack trace:
#0 /home/jason/cypht/lib/modules_exec.php(175): Hm_Handler_imap_forward_attachments->process()
#1 /home/jason/cypht/lib/modules_exec.php(153): Hm_Module_Exec->run_handler_module()
#2 /home/jason/cypht/lib/dispatch.php(220): Hm_Module_Exec->run_handler_modules()
#3 /home/jason/cypht/lib/dispatch.php(190): Hm_Dispatch->process_request()
#4 /home/jason/cypht/index.php(50): Hm_Dispatch->__construct()
#5 {main}
  thrown in /home/jason/cypht/modules/imap/handler_modules.php on line 58```

**Comment by marclaporte** [comment]
Thanks, we'll take a look.
